#!/usr/bin/env bash
# Installing a web server

apt-get -y update
apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
