#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y upgrade

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
app-get -y update

apt-get -y install haproxy=2.5.\*

config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends

backend lb-backends
    balance roundrobin
    server 382441-web-01 52.4.201.182:80 check
    server 382441-web-02 100.25.182.71:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
